"""empty message

Revision ID: 755556dc86cb
Revises: 
Create Date: 2023-10-18 14:30:01.710565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755556dc86cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity')
    # ### end Alembic commands ###
