"""Added date column to User model

Revision ID: 7a2b5be29b1b
Revises: 9416c7afb2d4
Create Date: 2023-11-14 20:00:00.422493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2b5be29b1b'
down_revision = '9416c7afb2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calorie_intake', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calorie_intake')
        batch_op.drop_column('steps')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
