"""Add dashboard_image column

Revision ID: 9416c7afb2d4
Revises: ff3c60218393
Create Date: 2023-11-02 19:14:11.277886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9416c7afb2d4'
down_revision = 'ff3c60218393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dashboard_image')

    # ### end Alembic commands ###
